### ISSUE TITLE
Make the main testing script perform actual testing

### ISSUE THREAD

**Issue by elboyran** [ImproPhoto/pymicmac#27]
Currently the main testing script
[`run_workflow_test`](https://github.com/ImproPhoto/pymicmac/blob/master/tests/run_workflow_test.sh)
only runs workflow steps in sequence, but doesn't check if they pass. 

For example, check at the end if the final pointcloud (.ply file) was created. If not --> fail.

**Comment by romulogoncalves** [comment]
The issue depends on this issue:
https://github.com/ImproPhoto/pymicmac/issues/36

**Comment by sverhoeven** [comment]
Fixed with #41
