### ISSUE TITLE
Move Codacy project to organization

### ISSUE THREAD

**Issue by sverhoeven** [ImproPhoto/pymicmac#35]
The Codacy project for this repo is at https://www.codacy.com/app/c-meijer/pymicmac/dashboard
It should be under a organization.

Please create a `ImproPhoto` organization in Codacy, move the project and give me and @felipeZ admin access.

**Comment by cwmeijer** [comment]
gave @sverhoeven, @felipeZ and the rest of the pymicmac rights to the new organization
