### ISSUE TITLE
Installation fails.

### ISSUE THREAD

**Issue by romulogoncalves** [ImproPhoto/pymicmac#4]
romulo:improphoto$ cd pymicmac
romulo:pymicmac$ virtualenv env
Running virtualenv with interpreter /usr/bin/python2
New python executable in /mnt/c/Users/Romulo/Projects/TEAM/improphoto/pymicmac/env/bin/python2
Also creating executable in /mnt/c/Users/Romulo/Projects/TEAM/improphoto/pymicmac/env/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
romulo:pymicmac$ . env/bin/activate
(env) romulo:pymicmac$ pip install .
Processing /mnt/c/Users/Romulo/Projects/TEAM/improphoto/pymicmac
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-zW1BVq-build/setup.py", line 6, in <module>
        if out.decode(sys.stdout.encoding).count('MicMac') == 0:
    TypeError: decode() argument 1 must be string, not None

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-zW1BVq-build/

**Comment by cwmeijer** [comment]
works on my machine (and on Travis ;-) )
